In [1]:
import numpy as np

In [9]:

print("3.1")

list = [20,27,9,12,31,17,4,50,39,35]

arr = np.array(list)

print("Array multiplied by 4:", arr * 4)

print(f"Mean: {np.mean(arr)}")

print(f"Median: {np.median(arr)}")

print(f"Standard Deviation: {np.std(arr):.2f}")

min = np.argmin(arr)

max = np.argmax(arr)

print(f"Index of smallest: {min}, Index of largest: {max}")

print(f"Value at min: {arr[min]}, Value at max_idx: {arr[max]}")

print(f"np.min(): {np.min(arr)}, np.max(): {np.max(arr)}")

print("Yes, the do match")

greater_than_20 = arr[arr > 20]

print("Values greater than 20:", greater_than_20)

3.1
Array multiplied by 4: [ 80 108  36  48 124  68  16 200 156 140]
Mean: 24.4
Median: 23.5
Standard Deviation: 13.83
Index of smallest: 6, Index of largest: 7
Value at min: 4, Value at max_idx: 50
np.min(): 4, np.max(): 50
Yes, the do match
Values greater than 20: [27 31 50 39 35]


In [ ]:
print(3.2)

matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])


rows, cols = matrix.shape

print(f"Shape: {matrix.shape} | Rows: {rows}, Columns: {cols}")

print("Three rows, four columns")

print("Third Column:", matrix[:, 2]) 

print("Second Row:", matrix[1, :])


print("Matrix * 2:\n", matrix * 2)


print("Mean of each column (axis=0):", np.mean(matrix, axis=0))

print("Overall Mean:", np.mean(matrix))


print("Max in each row (axis=1):", np.max(matrix, axis=1))

print("Min in each column (axis=0):", np.min(matrix, axis=0))

flat = matrix.flatten()

print(f"Flattened shape: {flat.shape} | 3D collapsed into 1D|Flat shape is 1 x 12")


min_flat = np.argmin(flat)

max_flat = np.argmax(flat)

min_coords = np.unravel_index(min_flat, matrix.shape)

max_coords = np.unravel_index(max_flat, matrix.shape)

print(f"Smallest (3) is at row {min_coords[0]}, col {min_coords[1]}")

print(f"Largest (21) is at row {max_coords[0]}, col {max_coords[1]}")


print("Values > 15:", matrix[matrix > 15])


print("Sorted Rows:\n", np.sort(matrix, axis=1))

3.2
Shape: (3, 4) | Rows: 3, Columns: 4
Three rows, four columns
Third Column: [17 14 19]
Second Row: [ 8 21 14  3]
Matrix * 2:
 [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
Mean of each column (axis=0): [ 6.33333333 15.33333333 16.66666667  7.66666667]
Overall Mean: 11.5
Max in each row (axis=1): [17 21 19]
Min in each column (axis=0): [ 5 12 14  3]
Flattened shape: (12,) | 3D collapsed into 1D.
Smallest (3) is at row 1, col 3
Largest (21) is at row 1, col 1
Values > 15: [17 21 19]
Sorted Rows:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [13]:
print("4")



def is_prime(n):
     # Checks if a single number is prime.
    
    if n < 2: return False
    
    for i in range(2, int(n**0.5) + 1):
    
        if n % i == 0:
    
            return False
    
    return True

def find_prime_rows(arr):
    # Apply the is_prime check to every element in the array
    
    check_primes = np.vectorize(is_prime)
    
    prime_ = check_primes(arr)
    
    # Find rows where at least one value is True
    # axis=1 tells NumPy to look across each row
    row_has_prime = np.any(prime_, axis=1)
    
    # Use that boolean list to filter the original rows
    return arr[row_has_prime]


arr = np.array([
    [2, 3, 5],    
    [14, 6, 8],  
    [11, 13, 17], 
    [7, 10, 13]   
])

print("Rows with at least one prime:\n", find_prime_rows(arr))

4
Rows with at least one prime:
 [[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [26]:
print("5.1")


def create_8x8_zeros():
    #Returns an 8x8 NumPy array filled with zeros.
    return np.zeros((8, 8))


zeros_array = np.zeros((8, 8))

print(zeros_array)

print("Shape:", zeros_array.shape)

print("5.2")

alternating = zeros_array

alternating[1::2, 1::2] = 1

print(alternating)

print("5.3")

alternating[::2, ::2] = 1

print(alternating)

print("5.4")


import numpy as np

def reverse_():
    # Initialize an 8x8 array of zeros
    alternating_rev = np.zeros((8, 8))
    
   
    alternating_rev[::2, 1::2] = 1
    
  
    alternating_rev[1::2, ::2] = 1
    
    return alternating_rev


print(reverse_())



5.1
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Shape: (8, 8)
5.2
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
5.3
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
5.4
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
print("6")

import numpy as np

def expansion(words_array, num_spaces):
    
    # Multiplying a string by an integer repeats it. 
    # If num_spaces is 2, this becomes "  ".
    spacer = " " * num_spaces
    
   
    # The .join() method takes our spacer and inserts it between every letter of the word.
    def expand_single_word(word):
        return spacer.join(word)
        
    # Convert our single-word function into a function that works on a whole NumPy array.
    vectorized_expand = np.vectorize(expand_single_word)
    
  
    return vectorized_expand(words_array)


universe = np.array(['galaxy', 'clusters'])

print("Expansion with 1 space:")

print(expansion(universe, 1))

print("\nExpansion with 2 spaces:")

print(expansion(universe, 2))



6
Expansion with 1 space:
['g a l a x y' 'c l u s t e r s']

Expansion with 2 spaces:
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [30]:
print("7")


import numpy as np

def secondDimmest(stars):
    
    # Sort the array along the rows (axis=1) in ascending order
    sorted_stars = np.sort(stars, axis=1)

    return sorted_stars[:, -2]


# Using a seed ensures we generate the same random numbers for testing
np.random.seed(123)

stars_array = np.random.randint(500, 2000, (5, 5))

print("Original Star Clusters:\n", stars_array)


print("\nSecond Brightest/Dimmest Stars:")

print(secondDimmest(stars_array))


7
Original Star Clusters:
 [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]

Second Brightest/Dimmest Stars:
[1889 1647 1138 1863 1592]
